name: NexGen_KoTHs
main: org.mle.nexgenkoths.NexGenKoths
version: 0.4
author: MrLolEthan
softdepend: [Factions, Vault]

commands:
        koth:
                description: The main NexGen KoTHs command.
                usage: /<command> <Sub-Command> (Arguments)
                permission: nexgenkoths.main
                permission-message: You don't have permission to do that.
                aliases: [k, nexgenkoth, koths, nexgenkoths]
permissions:
        nexgenkoths.entercooldown.bypass:
                description: Allows the player to bypass the KoTH enter cooldown.
                default: false
        nexgenkoths.main:
                description: Allows the player to use the Koth command.
                default: op
        nexgenkoths.help:
                description: Allows the player to view the NexGen KoTHs help text using the "help" Sub-Command.
                default: op
        nexgenkoths.create:
                description: Allows the player to create KoTHs using the "create" Sub-Command.
                default: op
        nexgenkoths.wand:
                description: Allows the player to get the selector item using the "wand" Sub-Command.
                default: op
        nexgenkoths.list:
                description: Allows the player to list all loaded KoTHs using the "list" Sub-Command.
                default: op
        nexgenkoths.setflag:
                description: Allows the player to set flags on KoTHs using the "flag" Sub-Command.
                default: op
        nexgenkoths.viewflags:
                description: Allows the player to view the flags of a KoTH using the "viewflags" Sub-Command.
                default: op
        nexgenkoths.delete:
                description: Allows the player to delete KoTHs using the "delete" Sub-Command.
                default: op
        nexgenkoths.saveall:
                description: Allows the player to save all KoTHs using the "saveall" Sub-Command.
                default: op
        nexgenkoths.start:
                description: Allows the player to manually start a KoTH using the "start" Sub-Command.
                default: op
        nexgenkoths.reload:
                description: Allows the player to reload the plugin using the "reload" Sub-Command.
                default: op
        nexgenkoths.setloottable:
                description: Allows the player to set the LootTable that a KoTH uses using the "setloottable" Sub-Command.
                default: op
        nexgenkoths.viewloottable:
                description: Allows the player to view the LootTable that a KoTH uses using the "viewloottable" Sub-Command.
                default: op
        nexgenkoths.listloottables:
                description: Allows the player to view a list of the loaded LootTables using the "listloottables" Sub-Command.
                default: op
        nexgenkoths.loottablecontents:
                description: Allows the player to view the contents of a LootTable using the "loottablecontents" Sub-Command.
                default: op
        nexgenkoths.version:
                description: Allows the player to view the current plugin version using the "version" Sub-Command.
                default: op
        nexgenkoths.viewtimers:
                description: Allows the player to view the timers on a KoTH using the "viewtimers" Sub-Command.
                default: op
        nexgenkoths.update:
                description: Allows the player to update the plugin using the "update" Sub-Command.
                default: op